# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --rekor-url
      - https://rekor.sigstore.dev/
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: all

dockers:
  - id: image-amd64
    dockerfile: Dockerfile
    image_templates:
      - "ttl.sh/{{.Env.DOCKER_TAG}}:1h"

docker_signs:
  - id: image-amd64
    cmd: cosign
    args:
      - sign
      - --yes
      - --rekor-url
      - https://rekor.sigstore.dev/
      - "${artifact}"
    artifacts: all
    output: true
